# Generated by Django 3.2 on 2021-06-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as premium. ', verbose_name='Premium'),
        ),
    ]
