# Generated by Django 3.2 on 2021-05-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_membership_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='duration_period',
            field=models.CharField(choices=[('month', 'Month'), ('year', 'Year'), ('lifetime', 'Life Time')], default='month', max_length=100),
        ),
    ]
