# Generated by Django 3.2 on 2021-06-04 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20210603_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='datetime_of_payment',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='membership_status',
            field=models.IntegerField(choices=[(1, 'ACTIVATED'), (0, 'DEACTIVATED')], default=0),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILURE'), (3, 'PENDING')], default=3),
        ),
    ]
