# Generated by Django 3.2 on 2021-06-04 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20210604_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payhistory',
            name='amount',
        ),
    ]
