# Generated by Django 3.2 on 2021-06-12 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_remove_payhistory_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermembership',
            name='membership_status',
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='datetime_of_payment',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
