# Generated by Django 3.2 on 2021-04-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('favicon', models.ImageField(upload_to='images')),
                ('logo', models.ImageField(upload_to='images')),
                ('logo_2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('address', models.TextField(blank=True, max_length=1000, null=True)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=2000, null=True)),
                ('meta_tags', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Site Setup',
                'verbose_name_plural': 'Site Setup',
            },
        ),
    ]
