# Generated by Django 3.2 on 2021-06-23 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('favicon', models.ImageField(upload_to='images')),
                ('logo', models.ImageField(upload_to='images')),
                ('logo_2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('address', models.TextField(blank=True, max_length=1000, null=True)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('footer_text', models.TextField(blank=True, max_length=2000, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=2000, null=True)),
                ('meta_tags', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Site Setup',
                'verbose_name_plural': 'Site Setup',
            },
        ),
        migrations.CreateModel(
            name='InfoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('icon', models.CharField(help_text='favicon, fontawesome etc icon class name', max_length=100)),
                ('pagesection', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_set', to='website.pagesection')),
            ],
        ),
    ]
