# Generated by Django 3.2 on 2021-04-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_infocard_page_pagesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
