# Generated by Django 3.2 on 2021-04-23 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_page_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocard',
            name='pagesection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_set', to='website.pagesection'),
        ),
    ]
