# Generated by Django 3.2 on 2021-04-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={},
        ),
        migrations.RenameField(
            model_name='support',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='support',
            old_name='Phone',
            new_name='phone',
        ),
    ]
