# Generated by Django 3.2 on 2021-06-23 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('link', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('availability', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='products')),
                ('price', models.PositiveIntegerField()),
                ('deal_price', models.PositiveIntegerField(default=0)),
                ('changed_price', models.PositiveIntegerField(default=0)),
                ('redused_price', models.PositiveIntegerField(default=0)),
                ('on_sale', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'product',
            },
        ),
    ]
