# Generated by Django 3.2 on 2021-05-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20210503_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='redused_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
